# Generated by Django 5.0.2 on 2024-02-19 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('biography', models.TextField(blank=True, verbose_name='Biography')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='Death Date')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('genre', models.CharField(max_length=100, verbose_name='Genre')),
                ('publication_date', models.DateField(verbose_name='Publication Date')),
                ('description', models.TextField(verbose_name='Description')),
                ('total_count', models.PositiveIntegerField(default=1, verbose_name='Total Count')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.author', verbose_name='Author')),
            ],
        ),
    ]
